spring:
  datasource:
    url: jdbc:h2:mem:hwadee_fsc;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V1__init_h2.sql
