spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hwadee_fsc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V1__init.sql
      continue-on-error: true
